name: Build application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Build app
      run: npm run build

    - name: Test if build succeeds
      run: |
        if [ -d "build" ]; then
          echo "Build successful"
          exit 0
        else
          echo "Build failed"
          exit 1
        fi
